name: Build and deploy a container image to Azure Web Apps

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: webapp-practice-1-123123
  AZURE_WEBAPP_PACKAGE_PATH: './published'
  NETCORE_VERSION: '5.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version ${{ env.NETCORE_VERSION }}
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Publish
        run: dotnet publish --no-build -c Release -o ./published
        
      - name: Deploy to Azure WebApp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
#      - name: Publish Artifacts
#        uses: actions/upload-artifact@v1.0.0
#        with:
#          name: webapp
#          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}